### ISSUE TITLE
Rename code under spl_composites.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.testing#10]
See comments in pr #7 .

One issue is that this demonstrates testing an SPL operator, the fact it is a composite is irrelevant. Maybe that doesn't matter, but there does need to be a  high-level writeup (at the README ?) describing what is going on.

It is using an SPL composite to test the operator.

**Comment by ddebrunner** [comment]
I guess without the writeup I'm still a little unclear on the goal of the example:

a) This example demonstrates using an SPL _test_ composite to test an SPL operator. The SPL operator under test in this case is an SPL composite with a single SPL custom, but could be SPL composite containing a sub-graph or an SPL primitive operator (implemented in C++, Java, or Python). The SPL _test_ composite invokes the operator under test (in this case connecting it to a Beacon as a source) and then the Java or Python test apis are used to invoke the test composite and verify the correct data is produced.

or

b) This example demonstrates testing an SPL operator. The SPL operator under test in this case is an SPL composite with a single SPL custom, but could be SPL composite containing a sub-graph or an SPL primitive operator (implemented in C++, Java, or Python).

**Comment by chanskw** [comment]
Yes.. I need to spend time on some write up. 

This is the correct description of it:

a) This example demonstrates using an SPL test composite to test an SPL operator. The SPL operator under test in this case is an SPL composite with a single SPL custom, but could be SPL composite containing a sub-graph or an SPL primitive operator (implemented in C++, Java, or Python). The SPL test composite invokes the operator under test (in this case connecting it to a Beacon as a source) and then the Java or Python test apis are used to invoke the test composite and verify the correct data is produced.

**Comment by chanskw** [comment]
I am not seeing how (b) is a possibility.  The test composite is not a main composite and it cannot be run without something driving it.

**Comment by ddebrunner** [comment]
Don't understand the question, b) doesn't mention a test composite.

**Comment by chanskw** [comment]
We need to have better names for this thing... This is confusing to describe.

**Comment by ddebrunner** [comment]
Or be clear and consistent, the README uses "the SPL composite" to refer to two different items:

1. The operator that is being tested (that just happens to be an SPL composite)
2. The SPL test composite.

Once we have a writeup with an introduction and effectively a user story I think it will be clearer. Basically we are trying to test an operator, and are using a SPL test composite to help us. Eventually there will be two+ variants of this:
   - testing an operator directly from Java/Python (the operator is invoked directly a topology)
   - testing an operator using an SPL test composite (and why was a test composite used).

So my suggestion is probably that the top level is not `spl_composites`  but `operators`.

**Comment by chanskw** [comment]
OK... so you want to rename examples/spl_composites to examples/operators... and all the projects to be: com.ibm.streamsx.testing.examples.operators

Is this correct?

**Comment by chanskw** [comment]
Btw, the same strategy can be used for testing primitive functions, via the use of Custom operator to write the logic to invoke the functions.

**Comment by ddebrunner** [comment]
true for functions, but I think the user story is "I want to test an operator" and thus the lead is operators.

"I want to test a function" happens to use the same/similar technique but I don't think that means one would start out by looking for the technique (a test composite) rather than the goal (test a function or operator).

**Comment by ddebrunner** [comment]
Actually, I think the techniques are different, at least to some extent, in that one is the natural invocation of the operator under test, while the other is in someways forcing execution of a function to allow it to be tested. They both use SPL composites because that's just how SPL code is invoked.

**Comment by chanskw** [comment]
OK... done this rename and delivered to "develop" branch
