### ISSUE TITLE
Rename example operators SPL toolkits.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.testing#15]
Looking at the project names it's not obvious to me which contains the operator under test and which contains the test composite. Looking at them my thinking goes `com.ibm.streamsx.testing.examples.operators.app` just contains the app that demonstrates use of the composite, and thus `com.ibm.streamsx.testing.examples.operators.spl` must contain the operator under test, therefore where is the test composite? `spl` is not a descriptive term here.

I propose renaming:

`com.ibm.streamsx.testing.examples.operators.app` to `com.ibm.streamsx.testing.examples.operators`.
(lose the `app`)

Reason, this is the toolkit that contains the operator under test, and it happens to include a app that demonstrates the operator under test.

`com.ibm.streamsx.testing.examples.operators.spl` to  `com.ibm.streamsx.testing.examples.operators.testing`.

Reason, makes it clear this is testing support for the toolkit and is probably a good pattern to encourage.

**Comment by ddebrunner** [comment]
@chanskw Thoughts?

**Comment by chanskw** [comment]
I like:
com.ibm.streamsx.testing.examples.operators.app to com.ibm.streamsx.testing.examples.operators.
(lose the app)

I do not like:
com.ibm.streamsx.testing.examples.operators.spl to com.ibm.streamsx.testing.examples.operators.testing.

For some reason having testing appears twice bothers me.  :)  

What about:  com.ibm.streamsx.testing.examples.operators.testop

**Comment by ddebrunner** [comment]
I think we want to define a pattern so that if I have a toolkit `a.b.c` how do a name a toolkit that contains testing artifacts for `a.b.c`. Note that it may be more that operators that exist in such a testing toolkit.

I'm proposing `a.b.c.testing`.

Testing only appears twice because we are in the `streamsx.testing` project.

We could rename these example toolkits to something else, e..g something like `examples.operators` 
 or `testexamples.operators` since they are never going to be used as real toolkits.

**Comment by chanskw** [comment]
+ 1 on just renaming the examples to something else, maybe that will make it simpler.

What about:  com.ibm.streamsx.examples.operators - remove testing from the name?

**Comment by ddebrunner** [comment]
I think `com.ibm.streamsx.examples.operators` is a bit too general.

Since these are just examples of how to run a test I don't think it's needed that they are in a namespace that starts with 'com.ibm.streamsx`.

**Comment by ddebrunner** [comment]
I updated the pr to:
- have the lead in for the toolkits/namespaces/packages be `examples.operators`.
- Change the layout to have all test related artifacts under `tests.

**Comment by ddebrunner** [comment]
I'll merge the PR and any suggest any subsequent renaming/layout changes should be under a new PR.
