### ISSUE TITLE
Examples and guidelines needed for testing application code

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.testing#2]
I am writing this up for the initial discussions on what examples and guidelines are needed to help customers test their Streams application.  I think we need test examples for the following:

* Java Operators
* Java Functions
* Applications & functional transformations written with Java Application API
* Python Operators
* ~Python Functions~ (not supported)
* Applications & functional transformations written with Python Application API
* SPL composites and functions
* SPL applications
* Applications & functional transformations written in Scala
* Microservices
* Application comprising on multiple microservices

@ddebrunner @joergboe  What are your thoughts on this?

**Comment by ddebrunner** [comment]
Agreed, plus just to note that for these items it should be noted (with examples) that the all/portions of underlying code can be tested outside of a Streams context using standard Java/Scala/Python testing frameworks.

- Java Functions
- Python operators (need to verify)
- Python/Java/Scala functional transformations used in streaming applications

**Comment by ddebrunner** [comment]
As reference:

- Java Operators
  - Java mock framework sample: https://www.ibm.com/support/knowledgecenter/en/SSCRJU_3.2.1/com.ibm.swg.im.infosphere.streams.spl-java-operators.doc/api/com/ibm/streams/flow/javaprimitives/package-summary.html
- Python application
  - Sample: http://ibmstreams.github.io/streamsx.topology/doc/releases/1.7/pythondoc/streamsx.topology.tester.html

**Comment by chanskw** [comment]
I added @ddebrunner example about how to test with Python unittest to a wiki here:
https://github.com/IBMStreams/streamsx.testing/wiki/Testing-Primitive-Operators-with-Python-Unittest

**Comment by joergboe** [comment]
The main focus of a test framework for Streams Toolkits must be the fact, that test of all kinds of Streams operators and functions is possible in the target Streams environment in a transparent way.

**Comment by chanskw** [comment]
@joergboe can you please elaborate what "transparent way" means to you?  If you think of the Junit framework that is being used in the product, what are some of the pain points that you are trying to address in your scripting framework?

**Comment by markheger** [comment]
wiki is incomplete:
https://github.com/IBMStreams/streamsx.testing/wiki/Testing-Primitive-Operators-with-Python-Unittest
You need to describe
a) that the FTP composite/toolkit in tk directory needs to indexed externally with spl-make-toolkit
b) you need to decribe, how to set VCAP_SERVICES and STREAMING_ANALYTICS_SERVICE_NAME for bluemix test

**Comment by ddebrunner** [comment]
I don't think that was meant to be an "official" example, it was a copy & paste from a discussion in another issue.

**Comment by chanskw** [comment]
Right.. I just want to make sure that we do not lose the information.  It was used as the base to create a more complete example. 

https://github.com/IBMStreams/streamsx.testing/tree/develop/examples/operators

Feel free to add the missing information to the wiki or the example.  I think we all have write access to the wiki page.  Thanks!

**Comment by ddebrunner** [comment]
I think rather than updating the wiki, the focus should be on the real example started by @chanskw
