### ISSUE TITLE
Using git hub flow for development here

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.testing#4]
I should have opened an issue to discuss before I pushed out the changes...

But I have initialized the repository to use Git Hubflow.  What this means that the default branch is "develop" and the "master" branch is protected.

This describes the development process:
https://datasift.github.io/gitflow/IntroducingGitFlow.html

I am working on Java and Python samples for testing primitive operators.  I will do the work on feature branch before I merge to the "develop" branch.

Please let me know if you have any concern?

**Comment by joergboe** [comment]
Sure; I can use the development branch.

**Comment by joergboe** [comment]
Should we clean up the master branch now?

**Comment by chanskw** [comment]
Yes please!  I think we also need to think about how to organize this repository.  As this is not a regular toolkit repository.

**Comment by ddebrunner** [comment]
There might be a toolkit at `com.ibm.streamsx.testing` containing useful functionality, e.g. operators that generate a known sequence of tuples for testing.

Apart from that we may want to see what artifacts get generated in feature branches before trying to figure out a layout.

**Comment by chanskw** [comment]
Yep agreed!
