### ISSUE TITLE
Feedback on using topology for testing

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.testing#6]
I started a wiki page to collect experiences and pain points when using topology APIs for unit testing.

https://github.com/IBMStreams/streamsx.testing/wiki/Feedback-on-using-Topology-for-Testing

Please add if you have other experiences... or use this issue to discuss.

**Comment by ddebrunner** [comment]
Thanks for the feedback, I've been adding comments for some of the items.

The Data Scientist using a test with a dataset is an interesting example to work through.

**Comment by ddebrunner** [comment]
@chanskw `streamsx` has been updated to 1.7.4 and includes a couple of fixes related to testing.

1. You can now use `nose` to run tests
2. Some bug fixes where the wrong exception for a failing test was reported.
